UI updates
beryu/CustomizableActionSheet pull request #26
Opened 2018-02-23 09:31 UTC by MeteC

Hey there, I've made some changes for my own purposes that might be of interest in the main project.

1. Made it more obj-c friendly by adding @objc access to various customisable properties.
2. Buttons on the action sheet now automatically highlight on touch.
3. Item interval spacing is customisable per action sheet.
4. You can define a default font for the whole CustomizableActionSheetItem class to set app-wide font settings simply.

2018-03-11 03:05 UTC, beryu requested changes
Thanks for using and enhancing!

I reply per items what you listed.

> 1. Made it more obj-c friendly by adding @objc access to various customisable properties.

I think to should not adding `@objc`. Because of keeping as pure swift.
In current, it’s not problem to add `@objc` , but it may be disturb if we wanna use new feature of Swift in future.

> 2. Buttons on the action sheet now automatically highlight on touch.

It’s nice feature.
But coding style is not equal with existing codes. 
Please fix it.
(Ex. “There is no `self.`” “First variable name what start with `_`”)

> 3. Item interval spacing is customisable per action sheet.

This is nice feature too.

> 4. You can define a default font for the whole CustomizableActionSheetItem class to set app-wide font settings simply.

Currently, this needs is satisfied by subclassing `{CustomizableActionSheetItem`.
So I think it should be not merged to keep interface simpler.

2018-03-11 03:14 UTC, beryu commented on CustomizableActionSheet/CustomizableActionSheet.swift
> +  func darkerColor(shadeFactor: CGFloat = 0.85) -> UIColor? {
Make private this extension because of there is risk conflict with library user

2018-03-11 03:14 UTC, beryu commented on CustomizableActionSheet/CustomizableActionSheet.swift
> +  }
This property can be simpler by below.

```
public var backgroundColor: UIColor = UIColor.white {
  didSet {
    if let highlightColor = color.darkerColor() {
      self.backgroundHighlightColor = highlightColor
    }
  }
}
```

2018-03-11 03:14 UTC, beryu commented on CustomizableActionSheet/CustomizableActionSheet.swift
> +  private var backgroundHighlightColor: UIColor   = UIColor.white.darkerColor()!
Do not use force unwrap.
Force unwrap is very dangerous except `@IBOutlet` .

2018-03-23 11:14 UTC, MeteC commented
thanks @beryu - I'll take a look at that! :-)

2018-04-17 08:07 UTC, MeteC commented
Have made changes as requested, see what you think!

In summary:

1. Buttons on action sheet now automatically highlight on touch
2. Item interval spacing is customisable per action sheet.
3. (*new*) Items can have `upperMargin` value set, which adds spacing at the top of the item. This is so you can for example have a Cancel button at the bottom slightly apart from the rest of the buttons.

Code style reviewed, extra `@objc` access removed, static default fonts removed.

2024-07-10 04:19 UTC, closed without merging