Add configurable position
beryu/CustomizableActionSheet pull request #27
Opened 2018-03-07 23:35 UTC by gravitylow

Added the option to have the action sheet drop down from the top.

![Demo](https://i.imgur.com/n2NuxeC.gif)

Thanks for the great lib!

2018-03-11 03:21 UTC, beryu requested changes
This is very interested feature!
Please review my comments.

2018-03-11 03:21 UTC, beryu commented on CustomizableActionSheet/CustomizableActionSheet.swift
> +    let moveY: CGFloat!
Do not use force unwarp.
Please set default value.

2018-03-11 03:21 UTC, beryu commented on CustomizableActionSheet/CustomizableActionSheet.swift
> +    let moveY: CGFloat!
Force unwrap is not necessary in here.
Please remove it.

2018-03-12 18:40 UTC, gravitylow commented
Thanks for your comments! The changes have been made in 778952b -- please let me know if you'd like the commits squashed.

2018-03-13 00:58 UTC, beryu approved these changes
Thanks fixing!

2018-03-13 00:59 UTC, merged